---
# tasks file for ansible-role-cloudwatchagent

- include_tasks: rhel.yml
  when: ansible_distribution == 'RedHat'

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: amazon.yml
  when: ansible_distribution == 'Amazon'

- name: 'Enable Amazon CloudWatch Agent'
  service:
      name: 'amazon-cloudwatch-agent'
      enabled: true